export const SHOW_DIALOG = 'SHOW_DIALOG';
export const CREATE_REPORT = 'CREATE_REPORT';
export const DELETE_REPORT = 'DELETE_REPORT';
export const GET_REPORTS = 'GET_REPORTS';
export const SET_CURRENT_AIRCRAFT = 'SET_CURRENT_AIRCRAFT';
export const GET_AREA = 'GET_AREA';
